core/urls.py
from django.urls import path
from .views import (
    ItemDetailView,
    HomeView,
    add_to_cart,
    remove_from_cart,
    ShopView,
    OrderSummaryView,
    remove_single_item_from_cart,
    CheckoutView,
    PaymentView,
    AddCouponView,
    RequestRefundView,
    OrderView,
    CategoryView
)

app_name = 'core'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('category/<slug:slug>/', CategoryView.as_view(), name='category'),
    path('product/<slug>/', ItemDetailView.as_view(), name='product'),
    path('add-to-cart/<slug>/', add_to_cart, name='add-to-cart'),
    path('add_coupon/', AddCouponView.as_view(), name='add-coupon'),
    path('remove-from-cart/<slug>/', remove_from_cart, name='remove-from-cart'),
    path('shop/', ShopView.as_view(), name='shop'),
    path('order-summary/', OrderSummaryView.as_view(), name='order-summary'),
    path('remove-item-from-cart/<slug>/', remove_single_item_from_cart,name='remove-single-item-from-cart'),
    path('payment/<payment_option>/', PaymentView.as_view(), name='payment'),
    path('orders/', OrderView.as_view(), name='order-list'),
    path('request-refund/', RequestRefundView.as_view(), name='request-refund')
]

demo/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('core.urls', namespace='core')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

core/models.py
from django.conf import settings
from django.db import models
from django.db.models import Sum
from django.shortcuts import reverse
from django_countries.fields import CountryField
from django.utils import timezone

default=timezone.now

BRAND_CHOICES = (
    ('LG', 'Logitech'), 
    ('HX', 'HyperX'), 
    ('RZ', 'Razer'), 
    ('DR', 'Dareu')
)


CATEGORY_CHOICES = (
    ('KB', 'Keyboard'), 
    ('M', 'Mouse'), 
    ('MP', 'Microphone'), 
    ('HP', 'Headphone')
)

LABEL_CHOICES = (
    ('S', 'sale'),
    ('N', 'new'),
    ('P', 'promotion')
)

ADDRESS_CHOICES = (
    ('B', 'Billing'),
    ('S', 'Shipping'),
)


class Slide(models.Model):
    caption1 = models.CharField(max_length=100)
    caption2 = models.CharField(max_length=100)
    link = models.CharField(max_length=100)
    image = models.ImageField(help_text="Size: 1920x570")
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return "{} - {}".format(self.caption1, self.caption2)

class Brand(models.Model):
    name = models.CharField(max_length=200)
    country = models.CharField(max_length=200, blank=True, null=True)
    email = models.EmailField(max_length=200, blank=True, null=True)
    
    def __str__(self):
        return self.name
    
class Category(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField()
    description = models.TextField()
    image = models.ImageField()
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("core:category", kwargs={
            'slug': self.slug
        })


class Item(models.Model):
    id = models.BigAutoField(primary_key=True)
    brand = models.ForeignKey(Brand, on_delete=models.CASCADE, related_name='items', null=True)
    title = models.CharField(max_length=100)
    price = models.FloatField()
    discount_price = models.FloatField(blank=True, null=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='items')
    label = models.CharField(max_length=1, choices=[('N', 'New'), ('S', 'Sale'), ('P', 'Promotion'),
                                                    ('D', 'Default')])
    slug = models.SlugField(unique=True)
    stock_no = models.CharField(max_length=10)
    description_short = models.CharField(max_length=50)
    description_long = models.TextField()
    image = models.ImageField()
    subimage_1 = models.ImageField(null=True)
    subimage_2 = models.ImageField(null=True)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return f"{self.brand} - {self.category}"

    def get_absolute_url(self):
        return reverse("core:product", kwargs={'slug': self.slug})

    def get_add_to_cart_url(self):
        return reverse("core:add-to-cart", kwargs={'slug': self.slug})

    def get_remove_from_cart_url(self):
        return reverse("core:remove-from-cart", kwargs={'slug': self.slug})


class OrderItem(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return f"{self.quantity} of {self.item.title}"

    def get_total_item_price(self):
        return self.quantity * self.item.price

    def get_total_discount_item_price(self):
        return self.quantity * self.item.discount_price

    def get_amount_saved(self):
        return self.get_total_item_price() - self.get_total_discount_item_price()

    def get_final_price(self):
        if self.item.discount_price:
            return self.get_total_discount_item_price()
        return self.get_total_item_price()


class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    ref_code = models.CharField(max_length=20)
    items = models.ManyToManyField(OrderItem)
    start_date = models.DateTimeField(auto_now_add=True)
    ordered_date = models.DateTimeField()
    ordered = models.BooleanField(default=False)
    shipping_address = models.ForeignKey(
        'BillingAddress', related_name='shipping_address', on_delete=models.SET_NULL, 
        blank=True, null=True)
    billing_address = models.ForeignKey(
        'BillingAddress', related_name='billing_address', on_delete=models.SET_NULL, 
        blank=True, null=True)
    payment = models.ForeignKey(
        'Payment', on_delete=models.SET_NULL, blank=True, null=True)
    coupon = models.ForeignKey(
        'Coupon', on_delete=models.SET_NULL, blank=True, null=True)
    being_delivered = models.BooleanField(default=False)
    received = models.BooleanField(default=False)
    refund_requested = models.BooleanField(default=False)
    refund_granted = models.BooleanField(default=False)

    '''
    1. Item added to cart
    2. Adding a BillingAddress
    (Failed Checkout)
    3. Payment
    4. Being delivered
    5. Received
    6. Refunds
    '''

    def __str__(self):
        return self.user.username

    def get_total(self):
        total = 0
        for order_item in self.items.all():
            total += order_item.get_final_price()
        if self.coupon:
            total -= self.coupon.amount
        return total


class BillingAddress(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
    street_address = models.CharField(max_length=100)
    apartment_address = models.CharField(max_length=100)
    country = CountryField(multiple=False)
    zip = models.CharField(max_length=100)
    address_type = models.CharField(max_length=1, choices=ADDRESS_CHOICES)
    default = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username

    class Meta:
        verbose_name_plural = 'BillingAddresses'


class Payment(models.Model):
    stripe_charge_id = models.CharField(max_length=50)
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.SET_NULL, blank=True, null=True)
    amount = models.FloatField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username


class Coupon(models.Model):
    code = models.CharField(max_length=15)
    amount = models.FloatField()

    def __str__(self):
        return self.code


class Refund(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    reason = models.TextField()
    accepted = models.BooleanField(default=False)
    email = models.EmailField()

    def __str__(self):
        return f"{self.pk}"

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  {% include "header.html" %}

  <title>{% block head_title %}{% endblock %}</title>
  {% block extra_head %} {% endblock %}
  <style type="text/css">
    .form-control {
    display: block;
    width: 100%;
    height: calc(1.5em + .75rem + 2px);
    padding: .375rem .75rem;
    font-size: 1rem;
    font-weight: 400;
    line-height: 1.5;
    color: #495057;
    background-color: #fff;
    background-clip: padding-box;
    border: 1px solid #ced4da !important;
    border-radius: .25rem;
    transition: border-color .15s ease-in-out,box-shadow .15s ease-in-out;
}
  </style>
  <body class="animsition">
    {% include "nav.html"%}
    <div class="mt-2">
      {% if messages %} {% for message in messages %}
      <div
        class="alert alert-{{ message.tags }} alert-dismissible fade show"
        role="alert"
      >
        {{ message }}

        <button
          type="button"
          class="close"
          data-dismiss="alert"
          aria-label="Close"
        >
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    </div>

    {% endfor %} 
    {% endif %} 

    {% block content %} 
    {% endblock content %}

     {% block extra_body %} 
     {% endblock %} 

    {% include "footer.html"%} 
    {% include "script.html"%}

    {% block extra_scripts %}
    {% endblock extra_scripts %}
  </body>
</html>

templates/footer.html
{% load static %}
<!-- ------------------------------footer sub end---------------------------------- -->
<!-- Google Font -->
<link href="https://fonts.googleapis.com/css?family=Abel|Lato|Open+Sans&display=swap" rel="stylesheet">
<style>
#footer-main{
	background: #000;
	color: white;
	font-size: 0.8rem;
	padding: 2.5rem 0 ;
    font-family: 'Lato', sans-serif;
}

#footer-main a{
	font-size: 14px;
	display: block;
	margin: 0.3rem;
	color: grey;
}

#footer-main a:hover{
	font-weight: bold;
	color: white;
}

#footer-main h6 a{
    color: white;

    
}

#footer-main hr {
    margin-top: 1rem;
    margin-bottom: 1rem;
    border: 0;
    border-top: 1px solid white;
}

#footer-main img{
	margin-right: 0.6rem;
}
</style>

<footer id="footer-main">
    <div class="container">
      <div class="row">
        <div class="col-sm-3">
            <br>

            <h6 class="mt-3"><a href="">FIND A STORE</a></h6>
            <h6 class="mt-3"><a href="">SIGN UP FOR EMAIL</a></h6>
            <h6 class="mt-3"><a href="">BECOME A MEMBER</h6>
            
            <h6 class="mt-3"><a href="/admin/">ADMIN LOGIN</a></h6>
           
        </div>
        <div class="col-sm-3">
            <h6 class="mt-3"><a href="">GET HELP</a></h6>
            <a href="">Order Status</a>
            <a href="">Shipping and Delivery</a>
            <a href="">Returns</a>
            <a href="">Payment Options</a>
            <a href="">Contact Us</a>
        </div>
        <div class="col-sm-3">
            <h6 class="mt-3"><a href="">ABOUT LERCUMAR</a></h6>
            <a href="">News</a>
            <a href="">Careers</a>
            <a href="">Investors</a>
            <a href="">Sustainability</a>
            
            



        </div>
        <div class="col-sm-3">
          <a href="">Voice of Customer</a>
          <a href="">Contacts by Branch</a>
          <a href="">Ethics Reporting</a>
          <a href="">Careers</a>

          <br><br>
          <a href="">Business Inquiry</a>
          <br>
          <a href="" class="ico"><i class="fab fa-apple fa-2x"></i> Apple Store</a>
          <a href="" class="ico"><i class="fab fa-google-play fa-2x"></i> Google Play</a>
        </div>
      </div>
      <hr>
      <div class="row">
        <div class="col-sm-6">
          
        </div>
        <div class="col-sm-6">
          
        </div>
        <hr>
        <a href="#" style="margin-left: 1rem">Privacy Policy | @G03 TAUKY 2024</a>
      </div>
    </div>
  </footer>
<!-- ------------------------------footer end---------------------------------- -->

templates/item_list.html
{% extends "base.html" %} {% block content %}

<h2>Here is the list of items</h2>

{% endblock content%}

templates/nav.html
{% load static %}
{% load cart_template_tags %}
{% load category_template_tags %}


<style>
	.topbar {
		background-color: black;
		color: white !important;
	}
	.topbar a:hover{
		color: white;
	}

	.right-align {
		display: flex;
		justify-content: flex-end;
		width: 100;
	}
</style>

<script>
    function updateClock() {
        var now = new Date();
        var day = now.getDate();
        var month = now.getMonth() + 1;
        var year = now.getFullYear();
        var hours = now.getHours();
        var minutes = now.getMinutes();
        var seconds = now.getSeconds();

        // Add leading zero to single-digit numbers
        day = day < 10 ? '0' + day : day;
        month = month < 10 ? '0' + month : month;
        hours = hours < 10 ? '0' + hours : hours;
        minutes = minutes < 10 ? '0' + minutes : minutes;
        seconds = seconds < 10 ? '0' + seconds : seconds;

        var dateTime = day + '/' + month + '/' + year + ' ' + hours + ':' + minutes + ':' + seconds;
        document.getElementById('clock').innerText = dateTime;
    }

    // Update clock every second
    setInterval(updateClock, 0);

    // Initial call to display clock immediately upon page load
    updateClock();

</script>
<!-- Header -->
<header class="header1">
		<!-- Header desktop -->
		<div class="container-menu-header">
			<div class="topbar">
				<div class="topbar-social">
					<a href="#" class="topbar-social-item fab fa-facebook"></a>
					<a href="#" class="topbar-social-item fab fa-instagram"></a>
					<a href="#" class="topbar-social-item fab fa-pinterest-p"></a>
					<a href="#" class="topbar-social-item fab fa-twitter"></a>
					<a href="#" class="topbar-social-item fab fa-youtube"></a>
				</div>

				<span class="topbar-child1" style="font-family:Kanit">
					จัดส่งฟรีเมื่อสั่งครบ ฿5000 ขึ้นไป
				</span>

				<div class="topbar-child2">
					<p class="navbar-text" style="color: #888888; font-weight: bold; font-size: 13px;" id="clock"></p>
				</div>
			</div>
			

			<div class="wrap_header">
				<!-- Logo -->
				<a href="/" class="logo">
					<p style="color: black; "><b style="font-size: 22px;">LERCUMAR</b></p>
				</a>

				<!-- Menu -->
				<div class="wrap_menu">
					<nav class="menu">
						<ul class="main_menu">
								<li class="dropdown">
									<a href="/shop/" class="dropdown-toggle" data-toggle="dropdown">Shop</a>
									<ul class="sub_menu">
										<li><a href="/shop/">All Categories</a></li>
										{% categories_li_a %}
									</ul>
								</li>
							
							
								{% if request.user.is_authenticated %}
							
								<li>
									<div class="header-wrapicon2">
										<a href="{% url 'core:order-summary' %}">
											<img src="{% static 'images/icons/icon-header-02.png' %}" class="header-icon1 js-show-header-dropdown" alt="ICON">
											<span class="header-icons-noti">{{ request.user|cart_item_count }}</span>
										</a>
									</div>
								</li>


								<li class="dropdown">
										<a href="#" class="dropdown-toggle" data-toggle="dropdown">{{ user.username }}</a>
										<ul class="sub_menu">
											{% if request.user.is_staff %}
											<li><a href="/admin/">Admin</a></li> 
											{% endif %}
											<li><a href="/orders/">Your Orders</a></li>
											<li><a href="{% url 'account_logout' %}">Logout</a></li>
										</ul>
									</div>
								</li>

								{% else %}
								<li class="dropdown">
										<a href="#" class="dropdown-toggle" data-toggle="dropdown">Guest</a>
										<ul class="sub_menu">
											<li><a href="{% url 'account_login' %}">Login</a></li>
											<li><a href="{% url 'account_signup' %}">Signup</a></li>
										</ul>
									</div>
								</li>		
								{% endif %}
								
						</ul>
					</nav>
				</div>

				
			</div>
		</div>

		<!-- Header Mobile -->
		<div class="wrap_header_mobile">
			<!-- Logo moblie -->
			<a href="/" class="logo-mobile">
				<p style="color: black; "><b style="font-size: 22px;">LERCUMAR</b></p>
			</a>

			<!-- Button show menu -->
			<div class="btn-show-menu">
				<!-- Header Icon mobile -->
				<div class="header-icons-mobile">
					<a href="#" class="header-wrapicon1 dis-block">
						<img src="{% static 'images/icons/icon-header-01.png' %}" class="header-icon1" alt="ICON">
					</a>

					<span class="linedivide2"></span>

					<div class="header-wrapicon2">
						<img src="{% static 'images/icons/icon-header-02.png' %}" class="header-icon1 js-show-header-dropdown" alt="ICON">
						<span class="header-icons-noti">{{ request.user|cart_item_count }}</span>

						<!-- Header cart noti -->
						<div class="header-cart header-dropdown">
							<ul class="header-cart-wrapitem">
								<li class="header-cart-item">
									<tbody>
										{% for order_item in object.items.all %}
										<tr>
										  <th scope="row">{{ forloop.counter }}</th>
										  <td>
												<img src="{{ order_item.item.image.url }}" style="width: 130px;"> 
										  </td>
										  <td>{{ order_item.item.title }}</td>
										  <td>{{ order_item.item.price }}</td>
										  <td>
											  <a href="{% url 'core:remove-single-item-from-cart' order_item.item.slug %}"><i class="fas fa-minus mr-3"></i></a>
											  {{ order_item.quantity }}
											  <a href="{% url 'core:add-to-cart' order_item.item.slug %}"><i class="fas fa-plus ml-3"></i></a>
										  </td>
										  <td>
											{% if order_item.item.discount_price %}
												${{ order_item.get_total_discount_item_price}}
												<span class="badge badge-primary">  Saving ฿{{ order_item.get_amount_saved }}</span>
											{% else %}
												${{ order_item.get_total_item_price}}
											{% endif %}
											<a style="color: red" href="{% url 'core:remove-from-cart' order_item.item.slug %}">
												<i class="fas fa-trash float-right"></i>
											</a>
										  </td>
										</tr>
										{% empty %}
										<tr>
											  <td colspan="5">Your cart is empty</td>
										</tr>
									</tbody>
									{% endfor %}
								</li>
							</ul>
							{% if object.get_total %}
							<div class="header-cart-total">
								Total: ${{ object.get_total }}
							</div>
							{% endif %}
							<div class="header-cart-buttons">
								<div class="header-cart-wrapbtn">
									<!-- Button -->
									<a href="{% url 'core:order-summary' %}" class="flex-c-m size1 bg1 bo-rad-20 hov1 s-text1 trans-0-4">
										View Cart
									</a>
								</div>

								<div class="header-cart-wrapbtn">
									<!-- Button -->
									<a href="/checkout" class="flex-c-m size1 bg1 bo-rad-20 hov1 s-text1 trans-0-4">
										Check Out
									</a>
								</div>
							</div>
						</div>
					</div>
				</div>

				<div class="btn-show-menu-mobile hamburger hamburger--squeeze">
					<span class="hamburger-box">
						<span class="hamburger-inner"></span>
					</span>
				</div>
			</div>
		</div>

		<!-- Menu Mobile -->
		<div class="wrap-side-menu" >
			<nav class="side-menu">
				<ul class="main-menu">
					<li class="item-topbar-mobile p-l-20 p-t-8 p-b-8">
						<span class="topbar-child1" style="font-family:Kanit">
							จัดส่งฟรีเมื่อสั่งครบ $5000 ขึ้นไป
						</span>
					</li>

					<li class="item-topbar-mobile p-l-20 p-t-8 p-b-8">
						<div class="topbar-child2-mobile">
							<span class="topbar-email">
								lercumar@gmail.com
							</span>

						</div>
					</li>

					<li class="item-topbar-mobile p-l-10">
						<div class="topbar-social-mobile">
							<a href="#" class="topbar-social-item fa fa-facebook"></a>
							<a href="#" class="topbar-social-item fa fa-instagram"></a>
							<a href="#" class="topbar-social-item fa fa-pinterest-p"></a>
							<a href="#" class="topbar-social-item fa fa-snapchat-ghost"></a>
							<a href="#" class="topbar-social-item fa fa-youtube-play"></a>
						</div>
					</li>

					<li class="item-menu-mobile">
						<a href="/">Home</a>
					</li>

					<li class="item-menu-mobile">
						<a href="/shop">Shop</a>
					</li>

					{% categories_mobile %}

					{% if request.user.is_authenticated %}
					<li class="item-menu-mobile">
						<a href="{% url 'core:order-summary' %}">Cart<span class="badge badge-dark">{{ request.user|cart_item_count }}</span></a>
					</li>
					<li class="item-menu-mobile">
						<a href="{% url 'account_logout' %}">Logout</a>
					</li>
					{% else %}
					<li class="item-menu-mobile">
						<a href="#">Login</a>
						<ul class="sub-menu">
							<li><a href="{% url 'account_login' %}">Login</a></li>
							<li><a href="{% url 'account_signup' %}">SignUp</a></li>
						</ul>
						<i class="arrow-main-menu fa fa-angle-right" aria-hidden="true"></i>
					</li>
					{% endif %}

				</ul>
			</nav>
		</div>
	</header>
	

templates/order_snippet.html
   <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
      .form-control {
    display: block;
    width: 100%;
    height: calc(1.5em + .75rem + 2px);
    padding: .375rem .75rem;
    font-size: 1rem;
    font-weight: 400;
    line-height: 1.5;
    color: #495057;
    background-color: #fff;
    background-clip: padding-box;
    border: 1px solid #ced4da !important;
    border-radius: .25rem;
    transition: border-color .15s ease-in-out,box-shadow .15s ease-in-out;
}


    </style>
  
 
    

   

    <div class="col-md-4 order-md-2 mb-4" style="background: #fff;">
      <h4 class="d-flex justify-content-between align-items-center mb-3">
        <span class="text-muted">Your cart</span>
        <span class="badge badge-secondary badge-pill">{{ order.items.count }}</span>
      </h4>
      <ul class="list-group mb-3">
        {% for order_item in order.items.all %}
        <li class="list-group-item d-flex justify-content-between lh-condensed">
          <div>
            <h6 class="my-0">{{ order_item.item.title }}</h6>
            <small class="text-muted">quantity : {{ order_item.quantity }}</small>
          </div>
          <span class="text-muted">฿{{ order_item.get_final_price }}</span>
        </li>
        {% endfor %}
        <li class="list-group-item d-flex justify-content-between bg-light">
          <div class="text-success">
            <h6 class="my-0">Promo code</h6>
            <small>{{order.coupon.code}}</small>
          </div>
          <span class="text-success">-฿{{ order.coupon.amount }}</span>
        </li>
        <li class="list-group-item d-flex justify-content-between">
          <span>Total (THB)</span>
          <strong>฿{{ order.get_total }}</strong>
        </li>
      </ul>
      
      {% if DISPLAY_COUPON_FORM %}
      <form method="POST" action="{% url 'core:add-coupon' %}" class="card p-2">
        {% csrf_token %}
        <div class="input-group">
          {{ couponform.code }}
          <div class="input-group-append">
            <button type="submit" class="btn btn-secondary">Redeem</button>
          </div>
        </div>
      </form>
      {% endif %}
    </div>

  

templates/order_summary.html
{% extends 'base.html' %} 
{% load static %} 
{% block content %}

<div class="container">
  <div class="row">
    <div class="col-lg-12">
      <h2>Order Summary</h2>
      <table class="table">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">Product Name</th>
            <th scope="col">Price</th>
            <th scope="col">Qty</th>
            <th scope="col">Total Price</th>
          </tr>
        </thead>
        <tbody>
          {% for order_item in object.items.all %}
          <tr>
            <th scope="row">{{ forloop.counter }}</th>
            <td>
			      <img src="{{ order_item.item.image.url }}" style="width: 130px;"> 
            </td>
            <td>{{ order_item.item.title }}</td>
            <td>{{ order_item.item.price }}</td>
            <td>
            	<a href="{% url 'core:remove-single-item-from-cart' order_item.item.slug %}"><i class="fas fa-minus mr-3"></i></a>
            	{{ order_item.quantity }}
            	<a href="{% url 'core:add-to-cart' order_item.item.slug %}"><i class="fas fa-plus ml-3"></i></a>
            </td>
            <td>
              {% if order_item.item.discount_price %}
                  ฿{{ order_item.get_total_discount_item_price}}
                  <span class="badge badge-primary">  Saving ฿{{ order_item.get_amount_saved }}</span>
              {% else %}
                  ฿{{ order_item.get_total_item_price}}
              {% endif %}
              <a style="color: red" href="{% url 'core:remove-from-cart' order_item.item.slug %}">
              	<i class="fas fa-trash float-right"></i>
              </a>
            </td>
          </tr>
          {% empty %}
          <tr>
			    <td colspan="5">Your cart is empty</td>
          </tr>
        </tbody>
        {% endfor %}
        {% if object.coupon %}
        <tr>
          <td colspan="5"><b>Coupon : </b></td>
          <td>- ฿{{ object.coupon.amount }}</td>
        </tr>
        {% endif%}
        {% if object.get_total %}
        <tr>
        	<td colspan="5"><b>Order Total : </b></td>
        	<td><b>฿{{ object.get_total }}</b></td>
        </tr>
        <tr>
        	<td colspan="5">
        		<a href="/checkout" class="btn btn-success float-right ml-2">Checkout</a>
        		<a href="/shop" class="btn btn-warning float-right">Continue Shopping</a>
        	</td>
        </tr>
        {% endif %}
      </table>
    </div>
  </div>
</div>

{% endblock content %}